CREATE DATABASE QLNHANSU2
On Primary
( Name=QLNHANSU_data, 
FileName='C:\QLNS2_DB\QLNHANSU.mdf', -- DOI DUONG DAN ( NEU MUON )
Size=50MB, 
MaxSize= Unlimited, 
FileGrowth=10MB  
),
FILEGROUP QLNHANSU_FG1
 ( NAME = 'QLNHANSU_FG1_Dat1',
 FILENAME='C:\QLNS2_DB\QLNHANSU_FG1_Dat1_01.ndf', -- DOI DUONG DAN ( NEU MUON )
 SIZE = 5MB,
 MAXSIZE=Unlimited,
 FILEGROWTH=1MB),
 ( NAME = 'QLNHANSU_FG1_Dat2',
 FILENAME ='C:\QLNS2_DB\QLNHANSU_FG1_Dat1_01_02.ndf', -- DOI DUONG DAN ( NEU MUON )
 SIZE = 5MB,
 MAXSIZE=Unlimited,
 FILEGROWTH=10%)
Log On
( Name=QLNHANSU_log,
FileName='C:\QLNS2_DB\QLNHANSU_log.ldf', -- DOI DUONG DAN
Size=50MB,
MaxSize=Unlimited,
FileGrowth=10MB
);

---Funtion AUTO_IDNV

CREATE FUNCTION AUTO_IDNV()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MANV) FROM tb_NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MANV, 3)) FROM tb_NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

---

USE [QLNHANSU]
GO
/****** Object:  Table [dbo].[tb_BANGCONG]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BANGCONG](
	[IDBC] [int] IDENTITY(1,1) NOT NULL,
	[NAM] [int] NULL,
	[THANG] [int] NULL,
	[NGAY] [int] NULL,
	[GIOVAO] [int] NULL,
	[PHUTVAO] [int] NULL,
	[GIORA] [int] NULL,
	[PHUTRA] [int] NULL,
	[MANV] [char](5) NULL,
	[IDLC] [int] NULL,
 CONSTRAINT [PK_tb_BANGCONG] PRIMARY KEY CLUSTERED 
(
	[IDBC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BAOHIEM]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BAOHIEM](
	[IDBH] [int] IDENTITY(1,1) NOT NULL,
	[SOBH] [nvarchar](50) NULL,
	[NGAYCAP] [datetime] NULL,
	[NOICAP] [nvarchar](50) NULL,
	[NOIDK] [nvarchar](50) NULL,
	[MANV] [char](5) NULL,
 CONSTRAINT [PK_tb_BAOHIEM] PRIMARY KEY CLUSTERED 
(
	[IDBH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BOPHAN]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BOPHAN](
	[IDBP] [int] IDENTITY(1,1) NOT NULL,
	[TENBP] [nvarchar](50) NULL,
 CONSTRAINT [PK_tb_BOPHAN] PRIMARY KEY CLUSTERED 
(
	[IDBP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_CHUCVU]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CHUCVU](
	[IDCV] [int] IDENTITY(1,1) NOT NULL,
	[TENCV] [nvarchar](50) NULL,
 CONSTRAINT [PK_tb_CHUCVU] PRIMARY KEY CLUSTERED 
(
	[IDCV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_HOPDONG]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_HOPDONG](
	[SOHD] [int] IDENTITY(1,1) NOT NULL,
	[NGAYBAYDAU] [datetime] NULL,
	[NGAYKETTHUC] [datetime] NULL,
	[NGAYKY] [datetime] NULL,
	[NOIDUNG] [nvarchar](max) NULL,
	[LANKY] [int] NULL,
	[THOIHAN] [nvarchar](50) NULL,
	[HESOLUONG] [float] NULL,
	[MANV] [char](5) NULL,
 CONSTRAINT [PK_tb_HOPDONG] PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_KHENTHUONG_KYLUAT]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_KHENTHUONG_KYLUAT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOKTKL] [int] NULL,
	[NOIDUNG] [nvarchar](500) NULL,
	[NGAY] [datetime] NULL,
	[MANV] [char](5) NULL,
	[LOAI] [int] NULL,
 CONSTRAINT [PK_tb_KHENTHUONG_KYLUAT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_LOAICA]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_LOAICA](
	[IDLOAICA] [int] IDENTITY(1,1) NOT NULL,
	[TENLOAICA] [nvarchar](50) NULL,
	[HESO] [float] NULL,
 CONSTRAINT [PK_tb_LOAICA] PRIMARY KEY CLUSTERED 
(
	[IDLOAICA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_LOAICONG]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_LOAICONG](
	[IDLC] [int] IDENTITY(1,1) NOT NULL,
	[TENLC] [nvarchar](50) NULL,
	[HESO] [float] NULL,
 CONSTRAINT [PK_tb_LOAICONG] PRIMARY KEY CLUSTERED 
(
	[IDLC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_NHANVIEN]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_NHANVIEN](
	[MANV] [char](5) CONSTRAINT IDNV DEFAULT DBO.AUTO_IDNV(),
	[HOTEN] [nvarchar](50) NULL,
	[GIOITINH] [bit] NULL,
	[NGAYSINH] [datetime] NULL,
	[DIENTHOAI] [nvarchar](50) NULL,
	[CCCD] [nvarchar](50) NULL,
	[DIACHI] [nvarchar](500) NULL,
	[HINHANH] [varbinary](max) NULL,
	[IDPB] [int] NULL,
	[IDBP] [int] NULL,
	[IDCV] [int] NULL,
	[IDTD] [int] NULL,
 CONSTRAINT [PK_tb_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_NHANVIEN_PHUCAP]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_NHANVIEN_PHUCAP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MANV] [char](5) NULL,
	[IDPC] [int] NULL,
	[NGAY] [datetime] NULL,
	[NOIDUNG] [nvarchar](500) NULL,
	[SOTIEN] [float] NULL,
 CONSTRAINT [PK_tb_NHANVIEN_PHUCAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_PHONGBAN]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_PHONGBAN](
	[IDPB] [int] IDENTITY(1,1) NOT NULL,
	[TENPB] [nvarchar](50) NULL,
 CONSTRAINT [PK_tb_PHONGBAN] PRIMARY KEY CLUSTERED 
(
	[IDPB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_PHUCAP]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_PHUCAP](
	[IDPC] [int] IDENTITY(1,1) NOT NULL,
	[TENPC] [nvarchar](50) NULL,
	[SOTIEN] [float] NULL,
 CONSTRAINT [PK_tb_PHUCAP] PRIMARY KEY CLUSTERED 
(
	[IDPC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_TANGCA]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_TANGCA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAM] [int] NULL,
	[THANG] [int] NULL,
	[NGAY] [int] NULL,
	[SOGIO] [float] NULL,
	[MANV] [char](5) NULL,
	[IDLOAICA] [int] NULL,
 CONSTRAINT [PK_tb_TANGCA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_TRINHDO]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_TRINHDO](
	[IDTD] [int] IDENTITY(1,1) NOT NULL,
	[TENTD] [nvarchar](50) NULL,
 CONSTRAINT [PK_tb_TRINHDO] PRIMARY KEY CLUSTERED 
(
	[IDTD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_UNGLUONG]    Script Date: 27/09/2022 8:26:28 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_UNGLUONG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAM] [int] NULL,
	[THANG] [int] NULL,
	[NGAY] [int] NULL,
	[SOTIEN] [float] NULL,
	[TRANGTHAI] [bit] NULL,
	[MANV] [char](5) NULL,
 CONSTRAINT [PK_tb_UNGLUONG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[tb_BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_BANGCONG_tb_LOAICONG] FOREIGN KEY([IDLC])
REFERENCES [dbo].[tb_LOAICONG] ([IDLC])
GO
ALTER TABLE [dbo].[tb_BANGCONG] CHECK CONSTRAINT [FK_tb_BANGCONG_tb_LOAICONG]
GO
ALTER TABLE [dbo].[tb_BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_BANGCONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_BANGCONG] CHECK CONSTRAINT [FK_tb_BANGCONG_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_BAOHIEM]  WITH CHECK ADD  CONSTRAINT [FK_tb_BAOHIEM_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_BAOHIEM] CHECK CONSTRAINT [FK_tb_BAOHIEM_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_HOPDONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_HOPDONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_HOPDONG] CHECK CONSTRAINT [FK_tb_HOPDONG_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_KHENTHUONG_KYLUAT]  WITH CHECK ADD  CONSTRAINT [FK_tb_KHENTHUONG_KYLUAT_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_KHENTHUONG_KYLUAT] CHECK CONSTRAINT [FK_tb_KHENTHUONG_KYLUAT_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_BOPHAN] FOREIGN KEY([IDBP])
REFERENCES [dbo].[tb_BOPHAN] ([IDBP])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_BOPHAN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_CHUCVU1] FOREIGN KEY([IDCV])
REFERENCES [dbo].[tb_CHUCVU] ([IDCV])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_CHUCVU1]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_PHONGBAN] FOREIGN KEY([IDPB])
REFERENCES [dbo].[tb_PHONGBAN] ([IDPB])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_PHONGBAN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_TRINHDO] FOREIGN KEY([IDTD])
REFERENCES [dbo].[tb_TRINHDO] ([IDTD])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_TRINHDO]
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP] CHECK CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_PHUCAP] FOREIGN KEY([IDPC])
REFERENCES [dbo].[tb_PHUCAP] ([IDPC])
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP] CHECK CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_PHUCAP]
GO
ALTER TABLE [dbo].[tb_TANGCA]  WITH CHECK ADD  CONSTRAINT [FK_tb_TANGCA_tb_LOAICA] FOREIGN KEY([IDLOAICA])
REFERENCES [dbo].[tb_LOAICA] ([IDLOAICA])
GO
ALTER TABLE [dbo].[tb_TANGCA] CHECK CONSTRAINT [FK_tb_TANGCA_tb_LOAICA]
GO
ALTER TABLE [dbo].[tb_TANGCA]  WITH CHECK ADD  CONSTRAINT [FK_tb_TANGCA_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_TANGCA] CHECK CONSTRAINT [FK_tb_TANGCA_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_UNGLUONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_UNGLUONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_UNGLUONG] CHECK CONSTRAINT [FK_tb_UNGLUONG_tb_NHANVIEN]
GO

--

--Them cot MANQL vao bang NHANVIEN
ALTER TABLE tb_NHANVIEN
ADD MA_NQL CHAR(5);

ALTER TABLE tb_NHANVIEN
DROP COLUMN MA_NQL;
-- Them cot TRUONGPHONG vao bang PHONGBAN
ALTER TABLE tb_PHONGBAN
ADD TRUONGPHONG CHAR(5);
--Them rang buoc cua TRUONGPHONG voi MANV
ALTER TABLE [dbo].[tb_PHONGBAN]  WITH CHECK ADD  CONSTRAINT [FK_tb_PHONGBAN_TRUONGPHONG_tb_NHANVIEN_MANV] FOREIGN KEY([TRUONGPHONG])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
--Them rang buoc cua MANQL voi MANV
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_MANQL_tb_NHANVIEN_MANV] FOREIGN KEY([MA_NQL])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV]);
---Them du lieu vao bang NHANVIEN
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDCV)
values (N'Nguyễn Tuấn Khoa', '0', '19951117',1000);
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Nguyễn Anh Khoa', '0', '19981013', 2002, 1001, 'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Đỗ Phúc Tân', '0', '19991101', 2002, 1007, 'NV002');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Nguyễn Thành Nam', '0', '20000327', 2002, 1007, 'NV002');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Hà Bùi Mạnh Hùng', '0', '19991112', 2002, 1007, 'NV002');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Phạm Thị Diệu Li', '1', '19981120', 2002, 1007, 'NV002');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Trần Văn Nam', '0', '19960123', 2003,1002, 'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Văn Minh Tuấn', '0', '19950812', 2003,1007, 'NV007');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Văn Tuấn Anh', '0', '19990910', 2003,1007, 'NV007');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Lê Thị Hoài Như', '1', '19990910', 2003,1007, 'NV007');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Luthor Lex', '0', '19951204', 2003,1007, 'NV007');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Nguyễn Anh Minh', '0', '19990410', 2004, 1003,'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Đào Minh Dũng', '0', '19971201',2004, 1007,'NV012');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Nguyễn Khoa Đàm', '0', '19980823',2004, 1007,'NV012');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Lê Bích Phương', '1', '19991230',2004, 1007,'NV012');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Lê Phương Anh', '1', '19990212',2004, 1007,'NV012');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Selena', '1', '19970802', 2005, 1004, 'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Kevin Phillip', '0', '19980103', 2005, 1007, 'NV017');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Alan Phillip', '0', '19980702', 2005, 1007, 'NV017');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Elena Coctta', '1', '19991217', 2005, 1007, 'NV017');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Đỗ Lê Hưng', '0', '20000712', 2005, 1007, 'NV017');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Trần Kim TIền', '1', '19960523', 2006, 1005, 'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Lê Thị Diễm', '1', '20010214', 2006, 1007, 'NV022');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH, IDPB, IDCV, MA_NQL)
values (N'Đào Minh Hạnh', '0', '19980717', 2006, 1007, 'NV022');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Nguyễn Thị Bích Thụy', '1', '20000125', 2006, 1007, 'NV022');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Trần Tuấn Minh', '0', '20010212', 2006, 1007, 'NV022');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Lê Công Doanh', '0', '19970130', 2007, 1006, 'NV001');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Trần Thị Minh Anh', '0', '20010516', 2007, 1007, 'NV027');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Nguyễn Hưng Nguyên', '0', '20000422', 2007, 1007, 'NV027');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Đỗ Thành Đạt', '0', '19990612', 2007, 1007, 'NV027');
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Hà Tuấn Khang', '0', '20011224', 2007, 1007, 'NV027');


--Them du lieu bang chuc vu
DBCC CHECKIDENT ('dbo.tb_CHUCVU', RESEED, 1000)

insert into tb_CHUCVU (TENCV)
values (N'Chủ Tịch Hội Đồng Quản Trị')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Điều Hành')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Tài Chính')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Công Nghệ')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Kinh Doanh')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Marketing')

insert into tb_CHUCVU (TENCV)
values (N'Giám Đốc Nhân Sự')

insert into tb_CHUCVU (TENCV)
values (N'Nhân Viên')

---Them du lieu vao bang BoPhan
DBCC CHECKIDENT ('dbo.tb_BOPHAN', RESEED, 3000)

insert into tb_BOPHAN(TENBP)
values (N'Kế Toán')

insert into tb_BOPHAN(TENBP)
values (N'Business Analyst')

insert into tb_BOPHAN(TENBP)
values (N'Development')

insert into tb_BOPHAN(TENBP)
values (N'System')

insert into tb_BOPHAN(TENBP)
values (N'Quality Control')

---Bang HESOLUONG
CREATE TABLE [dbo].[tb_HESOLUONG](
	[MAHSL] [char](4) CONSTRAINT IDHSL DEFAULT DBO.AUTO_IDHSL(),
	[BAC] [int] NULL,
	[NHOMNGACH] [char](20) NULL,
	[HESOLUONG] [float] NULL
 CONSTRAINT [PK_tb_HESOLUONG] PRIMARY KEY CLUSTERED 
(
	[MAHSL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE FUNCTION AUTO_IDHSL()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MAHSL) FROM tb_HESOLUONG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAHSL, 2)) FROM tb_HESOLUONG
		SELECT @ID = 'HV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
	RETURN @ID
END



drop table tb_HESOLUONG
drop function AUTO_IDHSL

insert into tb_HESOLUONG(BAC,NHOMNGACH,HESOLUONG)
values (1,N'Nhóm 1 (A3.1)',6.2)

insert into tb_HESOLUONG(BAC,NHOMNGACH,HESOLUONG)
values (2,N'Nhóm 2 (A3.2)',6.11)

insert into tb_HESOLUONG(BAC,NHOMNGACH,HESOLUONG)
values (1,N'Nhóm 1 (A2.2)',4.4)

insert into tb_HESOLUONG(BAC,NHOMNGACH,HESOLUONG)
values (2,N'Nhóm 2 (A2.2)',4.3)

insert into tb_HESOLUONG(BAC,NHOMNGACH,HESOLUONG)
values (3,N'Nhóm A1',3)

--Bang BIENDONGHSL

CREATE TABLE [dbo].[tb_BIENDONGHSL](
	[MAHSL] [char](4) NOT NULL,
	[NAMAPDUNG] DATE,
	[BAC] [int] NULL,
	[NHOMNGACH] [char](20) NULL,
	[HESOLUONG] [float] NULL
 CONSTRAINT [PK_tb_BIENDONGHSL] PRIMARY KEY CLUSTERED 
(
	[MAHSL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

--Bang PhongBan
DBCC CHECKIDENT ('dbo.tb_PHONGBAN', RESEED, 2008)

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Quản Trị','NV001')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Điều Hành','NV002')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Tài Chính','NV003')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Công Nghệ', 'NV012')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Kinh Doanh','NV017')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Marketing','NV022')

insert into tb_PHONGBAN(TENPB, TRUONGPHONG)
values(N'Phòng Nhân Sự','NV027')

--Them Du Lieu vao bang HopDong
insert into tb_NHANVIEN(HOTEN,GIOITINH,NGAYSINH)
values (N'Hà Tuấn Khang', '0', '20011224', 2007, 1007, 'NV027');

DBCC CHECKIDENT ('dbo.tb_HOPDONG', RESEED, 3002)

insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191120', '20191115', 'NV002');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191223', '20191218', 'NV003');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200412', '20200407', 'NV004');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20171203', '20171128', 'NV005');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191115', '20191110', 'NV006');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200122', '20200117', 'NV007');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200313', '20200308', 'NV008');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200510', '20200505', 'NV009');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200429', '20200424', 'NV010');

insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20181206', '20181201', 'NV011');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20220412', '20220407', 'NV012');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20180610', '20180605', 'NV013');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191223', '20191218', 'NV014');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200408', '20200403', 'NV015');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20171213', '20171208', 'NV016');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191010', '20191005', 'NV017');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20201009', '20201004', 'NV018');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20190422', '20190417', 'NV019');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200511', '20200506', 'NV020');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200429', '20200424', 'NV021');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20181206', '20181201', 'NV022');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20220412', '20220407', 'NV023');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191120', '20191115', 'NV024');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191111', '20191106', 'NV025');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191123', '20191118', 'NV026');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200826', '20200821', 'NV027');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20201023', '20201018', 'NV028');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20191212', '20191207', 'NV029');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200106', '20200101', 'NV030');
insert into tb_HOPDONG (NGAYBAYDAU, NGAYKY, MANV)
values ('20200523', '20200518', 'NV031');

-- Them du lieu vao bang TANGCA
DBCC CHECKIDENT ('dbo.tb_TANGCA', RESEED, 11001)
insert into tb_TANGCA(NGAY, THANG, NAM, MANV)
values (04,10,2020, 'NV023');
insert into tb_TANGCA(NGAY, THANG, NAM, MANV)
values (04,10,2020, 'NV013');
insert into tb_TANGCA(NGAY, THANG, NAM, MANV)
values (05,10,2020, 'NV019');
insert into tb_TANGCA(NGAY, THANG, NAM, MANV)
values (05,10,2020, 'NV028');
insert into tb_TANGCA(NGAY, THANG, NAM, MANV)
values (06,11,2020, 'NV016');

--Them Du Lieu Vao Bang BAOHIEM
--Function tu sinh so bao hiem
CREATE FUNCTION AUTO_MA_BH()
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @MABH VARCHAR(15)
	IF (SELECT COUNT(SOBH) FROM tb_BAOHIEM) = 0
		SET @MABH = '0'
	ELSE
		SELECT @MABH = MAX(RIGHT(SOBH, 2)) FROM tb_BAOHIEM
		SELECT @MABH = CASE
			WHEN @MABH >= 0 and @MABH < 9 THEN 'DN479122510020' + CONVERT(CHAR, CONVERT(INT, @MABH) + 1)
			WHEN @MABH >= 9 and @MABH <20 THEN 'DN40101161520' + CONVERT(CHAR, CONVERT(INT, @MABH) + 1)
			WHEN @MABH >= 20 THEN 'DN47912299020' + CONVERT(CHAR, CONVERT(INT, @MABH) + 1)
		END
	RETURN @MABH
END



ALTER TABLE tb_BAOHIEM ADD CONSTRAINT SOBH_TUDONG DEFAULT DBO.AUTO_MA_BH() FOR SOBH;

--them function vao cot SOBH

DBCC CHECKIDENT ('dbo.tb_BAOHIEM', RESEED, 4004)

--them du lieu vao bang SOBH
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191120', N'Hồ Chí Minh', 'Bệnh Viện Bình Thạnh', 'NV002')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191223', N'Hồ Chí Minh', N'TTYT Quận Đống Đa', 'NV003')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200412', N'Hồ Chí Minh', N'Bệnh Viện Đa Khoa TD-AG', 'NV004')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20171203', N'Hồ Chí Minh', N'Bệnh Viện 115', 'NV005')

insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191105', N'Hồ Chí Minh', N'Bệnh Viện 354 TCHC', 'NV006')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200122', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV007')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200313', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV008')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200510', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV009')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200429', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV010')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20181206', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV011')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20220412', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV012')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20180610', N'Hồ Chí Minh', N'Bệnh Viện Quận Bình Thạnh', 'NV013')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191223', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV014')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200408', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV015')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20171213', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV016')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191010', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV017')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20201009', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV018')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20190422', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV019')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200511', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV020')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200429', N'Hồ Chí Minh', N'Bệnh Viện 354/TCHC', 'NV021')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20181206', N'Hồ Chí Minh', N'Bệnh Viện Đa Khoa TT-AG', 'NV022')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20220412', N'Hồ Chí Minh', N'Bệnh Viện Đa Khoa TT-AG', 'NV023')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191120', N'Hồ Chí Minh', N'Bệnh Viện Đa Khoa TT-AG', 'NV024')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191111', N'Hồ Chí Minh', N'Bệnh Viện Đa Khoa TT-AG', 'NV025')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191123', N'Hồ Chí Minh', N'Bệnh Viện 115', 'NV026')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200826', N'Hồ Chí Minh', N'Bệnh Viện 115', 'NV027')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20201023', N'Hồ Chí Minh', N'Bệnh Viện 115', 'NV028')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20191212', N'Hồ Chí Minh', N'Bệnh Viện 115', 'NV029')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200106', N'Hồ Chí Minh', N'TTYT Quận Đống Đa', 'NV030')
insert into tb_BAOHIEM (NGAYCAP, NOICAP, NOIDK, MANV)
values ('20200523', N'Hồ Chí Minh', N'TTYT Quận Đống Đa', 'NV031')
--them du lieu vao bang phu cap

DBCC CHECKIDENT ('dbo.tb_PHUCAP', RESEED, 5000)
insert into tb_PHUCAP (TENPC, SOTIEN)
values (N'Phụ cấp theo chức vụ', 5000000)
insert into tb_PHUCAP (TENPC, SOTIEN)
values (N'Phụ cấp theo thâm niên', 4000000)
insert into tb_PHUCAP (TENPC, SOTIEN)
values (N'Phụ cấp khác', 2000000)
--Them du lieu vao bang trinh do
DBCC CHECKIDENT ('dbo.tb_TRINHDO', RESEED, 200)
insert into tb_TRINHDO (TENTD)
values(N'Cao Đẳng')
insert into tb_TRINHDO (TENTD)
values(N'Sinh Viên')
--Thay doi data type cua cot SOHD, BANGHD
ALTER TABLE tb_HOPDONG  
DROP CONSTRAINT PK_tb_HOPDONG;   
--Lay ten cua constraints
SELECT TABLE_NAME,
       CONSTRAINT_TYPE,CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME='tb_HOPDONG';
--
alter table tb_HOPDONG   
alter column SOHD nvarchar(50) not null

alter table tb_HOPDONG 
add MAHD nvarchar(50)

update tb_HOPDONG
set MAHD=SOHD

alter table tb_HOPDONG 
drop column MAHD

---
ALTER TABLE tb_HOPDONG
DROP CONSTRAINT PK__tb_HOPDO__603F20CE92060349;
--Procedure de tang MAHD

--Them Khoa chinh
alter table tb_HOPDONG alter column SOHD NVARCHAR(50) NOT NULL;
go
alter table tb_HOPDONG add primary key (SOHD);


---
--

--
CREATE FUNCTION AUTO_MA_HD()
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @MAHD VARCHAR(15)
	IF (SELECT COUNT(SOHD) FROM tb_HOPDONG) = 0
		SET @MAHD = '0'
	ELSE
		SELECT @MAHD = MAX(RIGHT(SOHD, 2)) FROM tb_HOPDONG
		SELECT @MAHD = CASE
			WHEN @MAHD >= 0 and @MAHD < 9 THEN 'HDLD000000' + CONVERT(CHAR, CONVERT(INT, @MAHD) + 1)
			WHEN @MAHD >= 9 and @MAHD <20 THEN 'HDLD00000' + CONVERT(CHAR, CONVERT(INT, @MAHD) + 1)
		END
	RETURN @MAHD
END
DROP FUNCTION AUTO_MA_HD
ALTER TABLE tb_HOPDONG ADD CONSTRAINT SOHD_TUDONG DEFAULT DBO.AUTO_MA_HD() FOR SOHD;
ALTER TABLE tb_HOPDONG DROP CONSTRAINT SOHD_TUDONG;


CREATE FUNCTION AUTO_MA_HD()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(SOHD) FROM tb_HOPDONG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(SOHD, 2)) FROM tb_HOPDONG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDLD00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDLD0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

--Them Du Lieu Vao Bang Loai Ca
insert into tb_LOAICA(TENLOAICA)
values (N'Ca Sáng')
insert into tb_LOAICA(TENLOAICA)
values (N'Ca Tối')
--Them Du Lieu Vao Bang Ung Luong

DBCC CHECKIDENT ('dbo.tb_UNGLUONG', RESEED, 6000)

insert into tb_UNGLUONG(NAM, THANG, NGAY, SOTIEN, TRANGTHAI, MANV)
values (2022,10,20,4000000,NULL, 'NV003')
insert into tb_UNGLUONG(NAM, THANG, NGAY, SOTIEN, TRANGTHAI, MANV)
values (2022,10,15,3500000,NULL, 'NV004')

--Them Du Lieu Vao Bang Cong

DBCC CHECKIDENT ('dbo.tb_BANGCONG', RESEED, 7000)

insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV002')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,5,17,0, 'NV003')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV004')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,30,17,0, 'NV005')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV006')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,15,17,0, 'NV007')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV008')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,16,50, 'NV009')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,30,17,0, 'NV010')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV011')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,15,17,0, 'NV012')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV013')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,23,17,0, 'NV014')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV015')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV016')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,10,17,0, 'NV017')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV018')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV019')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV020')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV021')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV022')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV023')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV024')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV025')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV026')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV027')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV028')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV029')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV030')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,28,7,0,17,0, 'NV031')

insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV002')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV003')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,5,17,0, 'NV004')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,15,17,0, 'NV005')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV006')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV007')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV008')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,10,16,59, 'NV009')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,8,30,17,0, 'NV010')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV011')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,15,17,0, 'NV012')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV013')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,23,17,0, 'NV014')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV015')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV016')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,10,17,0, 'NV017')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV018')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV019')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV020')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV021')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV022')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV023')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV024')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV025')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV026')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV027')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV028')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV029')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV030')
insert into tb_BANGCONG(NAM, THANG, NGAY, GIOVAO, PHUTVAO, GIORA, PHUTRA, MANV)
values (2022,10,29,7,0,17,0, 'NV031')
--Them Du Lieu Vao Bang BIENDONGHSL
insert into tb_BIENDONGHSL(MAHSL,NAMAPDUNG, BAC, NHOMNGACH, HESOLUONG)
values ('HS01','20221025', 1, N'Nhóm 1(A3.1)',6.2)

insert into tb_BIENDONGHSL(MAHSL,NAMAPDUNG, BAC, NHOMNGACH, HESOLUONG)
values ('HS02','20220925', 2, N'Nhóm 1(A3.2)',6.11)

insert into tb_BIENDONGHSL(MAHSL,NAMAPDUNG, BAC, NHOMNGACH, HESOLUONG)
values ('HS03','20221025', 1, N'Nhóm 1(A2.1)',4.4)

insert into tb_BIENDONGHSL(MAHSL,NAMAPDUNG, BAC, NHOMNGACH, HESOLUONG)
values ('HS04','20221025', 2, N'Nhóm 2(A2.2)',4.3)

insert into tb_BIENDONGHSL(MAHSL,NAMAPDUNG, BAC, NHOMNGACH, HESOLUONG)
values ('HS05','20221025', 3, N'Nhóm A1',3)
--Them du lieu vao bang NHANVIEN_PHUCAP
insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV002',5000, '20221001' , N'Phụ cấp chức vụ',5000000)

insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV006',5000, '20221001' , N'Phụ cấp chức vụ',5000000)

insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV012',5000, '20221001' , N'Phụ cấp chức vụ',5000000)

insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV017',5000, '20221001' , N'Phụ cấp chức vụ',5000000)

insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV022',5000, '20221001' , N'Phụ cấp chức vụ',5000000)

insert into tb_NHANVIEN_PHUCAP(MANV, IDPC, NGAY, NOIDUNG, SOTIEN)
values ('NV027',5000, '20221001' , N'Phụ cấp chức vụ',5000000)


--Them du lieu vao bang loai cong

DBCC CHECKIDENT ('dbo.tb_LOAICONG', RESEED, 301)

insert into tb_LOAICONG(TENLC)
values (N'Công Thường')

insert into tb_LOAICONG(TENLC)
values (N'Công Lễ')

--Tao bang thanh toan luong

CREATE TABLE [dbo].[tb_THANHTOANLUONG](
	[IDLUONG] [INT] IDENTITY(1,1) NOT NULL,
	[THANGTT] [INT] NULL,
	[NAMTT] [INT] NULL,
	[MANV] [CHAR](5) NULL,
	[MACC] [INT] NULL,
	[LUONGCT] [FLOAT] NULL,
	[THUETNCN] [FLOAT] NULL,
	[LUONG] [FLOAT] NULL,
	[ID] [int] NULL
 CONSTRAINT [PK_tb_TT_LUONG] PRIMARY KEY CLUSTERED 
(
	[IDLUONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[tb_THANHTOANLUONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_TTL_tb_NV] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])

ALTER TABLE [dbo].[tb_THANHTOANLUONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_TTL_tb_UL] FOREIGN KEY([ID])
REFERENCES [dbo].[tb_UNGLUONG] ([ID])

alter table tb_THANHTOANLUONG
add IDPC int



ALTER TABLE [dbo].[tb_THANHTOANLUONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_TTL_tb_PC] FOREIGN KEY([IDPC])
REFERENCES [dbo].[tb_PHUCAP] ([IDPC])
-- Xoa He So Luong Trong Hop Dong
alter table tb_HOPDONG
drop column HESOLUONG

alter table tb_HOPDONG
add MAHSL char(4)

ALTER TABLE [dbo].[tb_HOPDONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_HD_tb_HSL] FOREIGN KEY([MAHSL])
REFERENCES [dbo].[tb_HESOLUONG] ([MAHSL])

alter table tb_HOPDONG
drop column THOIHAN

alter table tb_KHENTHUONG_KYLUAT
add THANG int

alter table tb_KHENTHUONG_KYLUAT
add NAM int

--Xoa rang buoc tren bang cong va Bang Cong
alter table tb_BANGCONG
DROP CONSTRAINT FK_tb_BANGCONG_tb_LOAICONG

alter table tb_BANGCONG
DROP CONSTRAINT FK_tb_BANGCONG_tb_NHANVIEN
drop table tb_BANGCONG

--Tao Bang Cong Chi Tiet
CREATE TABLE [dbo].[tb_THANGCONGCHITIET](
	[MATHANGCONG] [int] NOT NULL,
	[MANV] [char](5) NOT NULL,
	[N1] [nvarchar](10) NULL,
	[N2] [nvarchar](10) NULL,
	[N3] [nvarchar](10) NULL,
	[N4] [nvarchar](10) NULL,
	[N5] [nvarchar](10) NULL,
	[N6] [nvarchar](10) NULL,
	[N7] [nvarchar](10) NULL,
	[N8] [nvarchar](10) NULL,
	[N9] [nvarchar](10) NULL,
	[N10] [nvarchar](10) NULL,
	[N11] [nvarchar](10) NULL,
	[N12] [nvarchar](10) NULL,
	[N13] [nvarchar](10) NULL,
	[N14] [nvarchar](10) NULL,
	[N15] [nvarchar](10) NULL,
	[N16] [nvarchar](10) NULL,
	[N17] [nvarchar](10) NULL,
	[N18] [nvarchar](10) NULL,
	[N19] [nvarchar](10) NULL,
	[N20] [nvarchar](10) NULL,
	[N21] [nvarchar](10) NULL,
	[N22] [nvarchar](10) NULL,
	[N23] [nvarchar](10) NULL,
	[N24] [nvarchar](10) NULL,
	[N25] [nvarchar](10) NULL,
	[N26] [nvarchar](10) NULL,
	[N27] [nvarchar](10) NULL,
	[N28] [nvarchar](10) NULL,
	[N29] [nvarchar](10) NULL,
	[N30] [nvarchar](10) NULL,
	[N31] [nvarchar](10) NULL,
	[NGAYCONG] [float] NULL,
	[NGAYPHEP] [float] NULL,
	[NGHIKHONGPHEP] [float] NULL,
	[CONGNGAYLE] [float] NULL,
	[CONGCHUNHAT] [float] NULL,
	[TONGNGAYCONG] [float] NULL,
 CONSTRAINT [PK_THANGCONGCHITIET_1] PRIMARY KEY CLUSTERED 
(
	[MATHANGCONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[tb_THANGCONG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MATHANGCONG] [int] NOT NULL,
	[THANG] [int] NULL,
	[NAM] [int] NULL,
	[KHOA] [bit] NULL,
	[NGAYTINHCONG] [datetime] NULL,
	[NGAYCONGTRONGTHANG] [float] NULL,
	[TRANGTHAI] [bit] NULL,
 CONSTRAINT [PK_THANGCONG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

-- Xoa cot cong ngay le, cong chu nhat
Alter table tb_THANGCONGCHITIET
drop column CONGNGAYLE

Alter table tb_THANGCONGCHITIET
drop column CONGCHUNHAT

--
alter table tb_THANGCONGCHITIET
add PRIMARY KEY (MATHANGCONG)
--Them khoa ngoai vao bang THANGCONGCHITIET

ALTER TABLE [dbo].[tb_THANGCONGCHITIET]  WITH CHECK ADD  CONSTRAINT [FK_tb_TCCT_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])

ALTER TABLE [dbo].[tb_THANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_TC_tb_TCCT] FOREIGN KEY([MATHANGCONG])
REFERENCES [dbo].[tb_THANGCONGCHITIET] ([MATHANGCONG])

--Xem khoa chinh trong database

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'

--Xoa bang LoaiCong
drop table tb_LOAICONG

alter table tb_HOPDONG
add LUONGBD float

update tb_HOPDONG
set LUONGBD=10000000

ALTER TABLE tb_THANHTOANLUONG
drop CONSTRAINT FK_tb_TTL_tb_PC
ALTER TABLE tb_THANHTOANLUONG
drop column IDPC

update tb_HOPDONG
set MAHSL='HV04'