ALTER TABLE [dbo].[tb_BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_BANGCONG_tb_LOAICONG] FOREIGN KEY([IDLC])
REFERENCES [dbo].[tb_LOAICONG] ([IDLC])
GO
ALTER TABLE [dbo].[tb_BANGCONG] CHECK CONSTRAINT [FK_tb_BANGCONG_tb_LOAICONG]
GO
ALTER TABLE [dbo].[tb_BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_BANGCONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_BANGCONG] CHECK CONSTRAINT [FK_tb_BANGCONG_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_BAOHIEM]  WITH CHECK ADD  CONSTRAINT [FK_tb_BAOHIEM_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_BAOHIEM] CHECK CONSTRAINT [FK_tb_BAOHIEM_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_HOPDONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_HOPDONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_HOPDONG] CHECK CONSTRAINT [FK_tb_HOPDONG_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_KHENTHUONG_KYLUAT]  WITH CHECK ADD  CONSTRAINT [FK_tb_KHENTHUONG_KYLUAT_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_KHENTHUONG_KYLUAT] CHECK CONSTRAINT [FK_tb_KHENTHUONG_KYLUAT_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_BOPHAN] FOREIGN KEY([IDBP])
REFERENCES [dbo].[tb_BOPHAN] ([IDBP])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_BOPHAN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_CHUCVU1] FOREIGN KEY([IDCV])
REFERENCES [dbo].[tb_CHUCVU] ([IDCV])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_CHUCVU1]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_PHONGBAN] FOREIGN KEY([IDPB])
REFERENCES [dbo].[tb_PHONGBAN] ([IDPB])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_PHONGBAN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_tb_TRINHDO] FOREIGN KEY([IDTD])
REFERENCES [dbo].[tb_TRINHDO] ([IDTD])
GO
ALTER TABLE [dbo].[tb_NHANVIEN] CHECK CONSTRAINT [FK_tb_NHANVIEN_tb_TRINHDO]
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP] CHECK CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_PHUCAP] FOREIGN KEY([IDPC])
REFERENCES [dbo].[tb_PHUCAP] ([IDPC])
GO
ALTER TABLE [dbo].[tb_NHANVIEN_PHUCAP] CHECK CONSTRAINT [FK_tb_NHANVIEN_PHUCAP_tb_PHUCAP]
GO
ALTER TABLE [dbo].[tb_TANGCA]  WITH CHECK ADD  CONSTRAINT [FK_tb_TANGCA_tb_LOAICA] FOREIGN KEY([IDLOAICA])
REFERENCES [dbo].[tb_LOAICA] ([IDLOAICA])
GO
ALTER TABLE [dbo].[tb_TANGCA] CHECK CONSTRAINT [FK_tb_TANGCA_tb_LOAICA]
GO
ALTER TABLE [dbo].[tb_TANGCA]  WITH CHECK ADD  CONSTRAINT [FK_tb_TANGCA_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_TANGCA] CHECK CONSTRAINT [FK_tb_TANGCA_tb_NHANVIEN]
GO
ALTER TABLE [dbo].[tb_UNGLUONG]  WITH CHECK ADD  CONSTRAINT [FK_tb_UNGLUONG_tb_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[tb_UNGLUONG] CHECK CONSTRAINT [FK_tb_UNGLUONG_tb_NHANVIEN]
GO


--Them rang buoc cua TRUONGPHONG voi MANV
ALTER TABLE [dbo].[tb_PHONGBAN]  WITH CHECK ADD  CONSTRAINT [FK_tb_PHONGBAN_TRUONGPHONG_tb_NHANVIEN_MANV] FOREIGN KEY([TRUONGPHONG])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV])
--Them rang buoc cua MANQL voi MANV
ALTER TABLE [dbo].[tb_NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_tb_NHANVIEN_MANQL_tb_NHANVIEN_MANV] FOREIGN KEY([MA_NQL])
REFERENCES [dbo].[tb_NHANVIEN] ([MANV]);


CREATE TABLE [dbo].[tb_HESOLUONG](
	[MAHSL] [char](4) CONSTRAINT IDHSL DEFAULT DBO.AUTO_IDHSL(),
	[BAC] [int] NULL,
	[NHOMNGACH] [char](20) NULL,
	[HESOLUONG] [float] NULL
 CONSTRAINT [PK_tb_HESOLUONG] PRIMARY KEY CLUSTERED 
(
	[MAHSL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[tb_BIENDONGHSL](
	[MAHSL] [char](4) NOT NULL,
	[NAMAPDUNG] DATE,
	[BAC] [int] NULL,
	[NHOMNGACH] [char](20) NULL,
	[HESOLUONG] [float] NULL
 CONSTRAINT [PK_tb_BIENDONGHSL] PRIMARY KEY CLUSTERED 
(
	[MAHSL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

